name: CI Pipeline for OCProjet7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Installer Python et les dépendances
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 3. Lancer les tests unitaires
    - name: Run tests
      run: |
        pytest test_app.py

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    # 1. Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Installer les dépendances
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 3. Déployer l'API avec ngrok
    - name: Deploy with ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        nohup uvicorn app:app --host 0.0.0.0 --port 8000 --reload &
        ngrok http 8000


